  disk_exclusions:
    <<: *focal-common
    raids:
      os:
        <<: *raid1
        swap_size: 0
        mountpoint: /
        filesystem: ext4
        match_on:
          tags:
            - ssd
          size_lessthan: 300G
          max_devices: 2
        bootable: true
    drive_exclude:
      data_disks:
        match_on:
          size_greaterthan: 800G
    networking:
      interfaces:
        bond0:
          bonded: true
          slaves:
            by_mac:
              in_csv:
          networks:
            primary:
              in_csv:
              default_gateway: true
              vlans:
                internal:
                  in_csv:
    user_data:
      runcmd:
        - userdel -r ubuntu
        - rm -f /root/.ssh/authorized_keys
        - FQDN=$(hostname -f) ; sed -i -e "s/certname.*$/certname          =\ ${FQDN}/g" /etc/puppetlabs/puppet/puppet.conf 
        - systemctl enable puppet 
        - systemctl start puppet
        - echo "/opt/puppetlabs/bin/puppet agent -t" | at now + 1 minute
